In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OrdinalEncoder

In [ ]:
df=pd.read_csv('customer.csv')

In [ ]:
df.head()

   age  gender   review education purchased
0   30  Female  Average    School        No
1   68  Female     Poor        UG        No
2   70  Female     Good        PG        No
3   72  Female     Good        PG        No
4   16  Female  Average        UG        No

In [ ]:
# we will use sklearn ordinal encoder because pandas getdummies dont keep order

In [ ]:
X=df.drop('purchased',axis=1)
y=df['purchased']

In [ ]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

In [ ]:
df['education'].value_counts()

education
PG        18
School    16
UG        16
Name: count, dtype: int64

In [ ]:
df['review'].value_counts()

review
Poor       18
Good       18
Average    14
Name: count, dtype: int64

In [ ]:
encoder=OrdinalEncoder(categories=[['School','PG','UG'],['Poor','Average','Good']])

In [ ]:
X_train[['education','review']]=encoder.fit_transform(X_train[['education','review']])

In [ ]:
X_train

    age  gender  review  education
33   89  Female     2.0        1.0
35   74    Male     0.0        0.0
26   53  Female     0.0        1.0
34   86    Male     1.0        0.0
18   19    Male     2.0        0.0
7    60  Female     0.0        0.0
14   15    Male     0.0        1.0
45   61    Male     0.0        1.0
48   39  Female     2.0        2.0
29   83  Female     1.0        2.0
15   75    Male     0.0        2.0
30   73    Male     1.0        2.0
32   92    Male     1.0        2.0
16   59    Male     0.0        2.0
42   30  Female     2.0        1.0
20   57  Female     1.0        0.0
43   27    Male     0.0        1.0
8    65  Female     1.0        2.0
13   57  Female     1.0        0.0
25   57  Female     2.0        0.0
5    31  Female     1.0        0.0
17   22  Female     0.0        2.0
40   39    Male     2.0        0.0
49   25  Female     2.0        2.0
1    68  Female     0.0        2.0
12   51    Male     0.0        0.0
37   94    Male     1.0        1.0
24   16  Female     1.0        1.0
6    18    Male     2.0        0.0
23   96  Female     2.0        0.0
36   34  Female     2.0        2.0
21   32    Male     1.0        1.0
19   97    Male     0.0        1.0
9    74    Male     2.0        2.0
39   76    Male     0.0        1.0
46   64  Female     0.0        1.0
3    72  Female     2.0        1.0
0    30  Female     1.0        0.0
47   38  Female     2.0        1.0
44   77  Female     1.0        2.0