In [7]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OrdinalEncoder

In [8]:
df=pd.read_csv('cars.csv')

In [5]:
df.head()

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [11]:
X=df.drop('selling_price',axis=1)
y=df['selling_price']

In [12]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

In [13]:
ohe=OrdinalEncoder()

In [18]:
X_train[['fuel','brand','owner']]=ohe.fit_transform(X_train[['fuel','brand','owner']])

In [19]:
X_train

      brand  km_driven  fuel  owner
3042   11.0      60000  11.0    0.0
1520   27.0     150000  27.0    4.0
2611   11.0     110000  11.0    2.0
3544   19.0      28000  19.0    2.0
4138   20.0      15000  20.0    0.0
...     ...        ...   ...    ...
4931   27.0      70000  27.0    4.0
3264    9.0     100000   9.0    2.0
1653   11.0      90000  11.0    2.0
2607   29.0      90000  29.0    0.0
2732   11.0     110000  11.0    0.0

[6502 rows x 4 columns]