In [154]:
from sklearn.linear_model import SGDRegressor
import seaborn as sns 
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split
import pandas as pd
from sklearn.preprocessing import StandardScaler

In [155]:
df=sns.load_dataset('tips')

In [156]:
df.sample()

    total_bill  tip   sex smoker   day   time  size
89       21.16  3.0  Male     No  Thur  Lunch     2

In [157]:
df['time'].value_counts()

time
Dinner    176
Lunch      68
Name: count, dtype: int64

In [158]:
df.drop(['day'],axis=1,inplace=True)

In [159]:
df.sample()

     total_bill  tip   sex smoker    time  size
212       48.33  9.0  Male     No  Dinner     4

In [160]:
df = pd.get_dummies(df, columns=['sex', 'smoker', 'time'], drop_first=True, dtype=int)

In [161]:
X=df.drop('tip',axis=1)
y=df['tip']

In [162]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

In [163]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [164]:
X_train

array([[ 7.32409144e-01,  1.48790007e+00, -6.90849280e-01,
         7.65092056e-01,  6.18852748e-01],
       [ 1.36827467e+00, -6.22212755e-01, -6.90849280e-01,
        -1.30703226e+00, -1.61589329e+00],
       [-2.53182426e-01, -6.22212755e-01, -6.90849280e-01,
        -1.30703226e+00,  6.18852748e-01],
       [ 3.18607423e-02, -6.22212755e-01, -6.90849280e-01,
        -1.30703226e+00,  6.18852748e-01],
       [ 3.06647416e+00,  3.59801289e+00, -6.90849280e-01,
         7.65092056e-01,  6.18852748e-01],
       [-1.16203160e+00, -6.22212755e-01,  1.44749373e+00,
        -1.30703226e+00,  6.18852748e-01],
       [-8.95625874e-01, -6.22212755e-01, -6.90849280e-01,
        -1.30703226e+00,  6.18852748e-01],
       [ 1.06678671e+00,  1.48790007e+00, -6.90849280e-01,
         7.65092056e-01,  6.18852748e-01],
       [ 5.37871398e-02,  1.48790007e+00,  1.44749373e+00,
         7.65092056e-01,  6.18852748e-01],
       [-6.51146542e-01, -6.22212755e-01, -6.90849280e-01,
         7.65092056e-01, -1.61589329e+00],
       [-8.26557722e-01, -6.22212755e-01, -6.90849280e-01,
         7.65092056e-01,  6.18852748e-01],
       [ 7.76261939e-01, -6.22212755e-01, -6.90849280e-01,
        -1.30703226e+00,  6.18852748e-01],
       [-4.81216960e-01, -6.22212755e-01, -6.90849280e-01,
        -1.30703226e+00,  6.18852748e-01],
       [ 1.05314174e-01, -6.22212755e-01, -6.90849280e-01,
         7.65092056e-01, -1.61589329e+00],
       [ 5.26301007e-01,  1.48790007e+00,  1.44749373e+00,
         7.65092056e-01,  6.18852748e-01],
       [ 1.08980942e+00,  1.48790007e+00,  1.44749373e+00,
        -1.30703226e+00,  6.18852748e-01],
       [-5.11913917e-01, -6.22212755e-01, -6.90849280e-01,
        -1.30703226e+00,  6.18852748e-01],
       [-4.08859849e-01,  4.32843655e-01,  1.44749373e+00,
        -1.30703226e+00, -1.61589329e+00],
       [ 1.38471947e+00, -6.22212755e-01, -6.90849280e-01,
        -1.30703226e+00,  6.18852748e-01],
       [-1.08200025e+00,  4.32843655e-01,  1.44749373e+00,
         7.65092056e-01,  6.18852748e-01],
       [ 9.61539999e-01, -6.22212755e-01, -6.90849280e-01,
        -1.30703226e+00,  6.18852748e-01],
       [-5.28358715e-01, -6.22212755e-01,  1.44749373e+00,
        -1.30703226e+00,  6.18852748e-01],
       [-1.06226650e+00, -6.22212755e-01, -6.90849280e-01,
         7.65092056e-01,  6.18852748e-01],
       [ 4.81351892e-01,  1.48790007e+00,  1.44749373e+00,
         7.65092056e-01,  6.18852748e-01],
       [-6.45664942e-01, -6.22212755e-01,  1.44749373e+00,
        -1.30703226e+00,  6.18852748e-01],
       [-7.00480936e-01, -6.22212755e-01, -6.90849280e-01,
        -1.30703226e+00,  6.18852748e-01],
       [-1.70958435e-01,  4.32843655e-01,  1.44749373e+00,
         7.65092056e-01, -1.61589329e+00],
       [ 1.60179081e+00,  1.48790007e+00,  1.44749373e+00,
         7.65092056e-01,  6.18852748e-01],
       [-4.11052488e-01, -6.22212755e-01,  1.44749373e+00,
         7.65092056e-01,  6.18852748e-01],
       [-7.48719011e-01, -6.22212755e-01, -6.90849280e-01,
         7.65092056e-01,  6.18852748e-01],
       [-2.12618590e-01, -6.22212755e-01,  1.44749373e+00,
         7.65092056e-01, -1.61589329e+00],
       [-1.28153047e+00, -6.22212755e-01,  1.44749373e+00,
         7.65092056e-01, -1.61589329e+00],
       [-9.43863949e-01, -6.22212755e-01, -6.90849280e-01,
        -1.30703226e+00,  6.18852748e-01],
       [-4.56001603e-01,  4.32843655e-01, -6.90849280e-01,
         7.65092056e-01,  6.18852748e-01],
       [-1.93981153e-01,  1.48790007e+00, -6.90849280e-01,
         7.65092056e-01,  6.18852748e-01],
       [ 3.81586783e-01, -6.22212755e-01, -6.90849280e-01,
         7.65092056e-01,  6.18852748e-01],
       [-3.22250578e-01,  4.32843655e-01, -6.90849280e-01,
         7.65092056e-01,  6.18852748e-01],
       [-4.15926895e-02, -6.22212755e-01, -6.90849280e-01,
         7.65092056e-01,  6.18852748e-01],
       [-1.16751320e+00, -6.22212755e-01, -6.90849280e-01,
         7.65092056e-01,  6.18852748e-01],
       [-1.36594710e+00, -6.22212755e-01, -6.90849280e-01,
        -1.30703226e+00,  6.18852748e-01],
       [ 9.93434474e-03, -6.22212755e-01, -6.90849280e-01,
        -1.30703226e+00,  6.18852748e-01],
       [ 1.95261317e+00,  1.48790007e+00, -6.90849280e-01,
        -1.30703226e+00,  6.18852748e-01],
       [ 1.58205705e+00, -6.22212755e-01, -6.90849280e-01,
        -1.30703226e+00,  6.18852748e-01],
       [ 8.73834408e-01,  4.32843655e-01,  1.44749373e+00,
        -1.30703226e+00,  6.18852748e-01],
       [ 4.94018603e-02,  4.32843655e-01, -6.90849280e-01,
         7.65092056e-01,  6.18852748e-01],
       [ 2.75731196e+00,  4.32843655e-01, -6.90849280e-01,
        -1.30703226e+00,  6.18852748e-01],
       [ 2.87303274e-01,  4.32843655e-01, -6.90849280e-01,
         7.65092056e-01, -1.61589329e+00],
       [ 5.87694920e-01,  1.48790007e+00, -6.90849280e-01,
         7.65092056e-01,  6.18852748e-01],
       [ 1.71361543e+00,  4.32843655e-01,  1.44749373e+00,
         7.65092056e-01,  6.18852748e-01],
       [-8.32528449e-02, -6.22212755e-01, -6.90849280e-01,
        -1.30703226e+00, -1.61589329e+00],
       [-1.08638553e+00, -6.22212755e-01,  1.44749373e+00,
         7.65092056e-01,  6.18852748e-01],
       [-4.65868482e-01, -6.22212755e-01, -6.90849280e-01,
         7.65092056e-01, -1.61589329e+00],
       [-8.17787163e-01, -6.22212755e-01,  1.44749373e+00,
        -1.30703226e+00, -1.61589329e+00],
       [-1.22720360e-01, -6.22212755e-01, -6.90849280e-01,
         7.65092056e-01, -1.61589329e+00],
       [-7.85993886e-01, -6.22212755e-01, -6.90849280e-01,
         7.65092056e-01, -1.61589329e+00],
       [-1.08857817e+00, -6.22212755e-01, -6.90849280e-01,
         7.65092056e-01,  6.18852748e-01],
       [-6.63206060e-01, -6.22212755e-01,  1.44749373e+00,
         7.65092056e-01, -1.61589329e+00],
       [ 1.27728012e+00, -6.22212755e-01, -6.90849280e-01,
        -1.30703226e+00,  6.18852748e-01],
       [-1.28043415e+00, -6.22212755e-01, -6.90849280e-01,
         7.65092056e-01, -1.61589329e+00],
       [-3.00324181e-01, -6.22212755e-01, -6.90849280e-01,
         7.65092056e-01,  6.18852748e-01],
       [-5.88656309e-01, -6.22212755e-01,  1.44749373e+00,
         7.65092056e-01,  6.18852748e-01],
       [-8.23268762e-01, -6.22212755e-01, -6.90849280e-01,
         7.65092056e-01,  6.18852748e-01],
       [-8.39713561e-01, -6.22212755e-01, -6.90849280e-01,
         7.65092056e-01,  6.18852748e-01],
       [-7.43237411e-01, -6.22212755e-01,  1.44749373e+00,
        -1.30703226e+00, -1.61589329e+00],
       [-2.49893466e-01, -6.22212755e-01, -6.90849280e-01,
         7.65092056e-01,  6.18852748e-01],
       [-4.37364165e-01,  4.32843655e-01,  1.44749373e+00,
         7.65092056e-01,  6.18852748e-01],
       [ 2.22620401e-01, -6.22212755e-01, -6.90849280e-01,
         7.65092056e-01,  6.18852748e-01],
       [ 6.14613790e-02, -6.22212755e-01, -6.90849280e-01,
         7.65092056e-01,  6.18852748e-01],
       [ 9.68117918e-01,  4.32843655e-01, -6.90849280e-01,
         7.65092056e-01,  6.18852748e-01],
       [ 1.42589050e-01,  1.48790007e+00, -6.90849280e-01,
         7.65092056e-01,  6.18852748e-01],
       [ 3.35590261e+00,  4.32843655e-01, -6.90849280e-01,
        -1.30703226e+00,  6.18852748e-01],
       [-1.00635418e+00, -6.22212755e-01, -6.90849280e-01,
        -1.30703226e+00,  6.18852748e-01],
       [-4.94372799e-01, -6.22212755e-01, -6.90849280e-01,
        -1.30703226e+00,  6.18852748e-01],
       [-4.06667209e-01,  1.48790007e+00, -6.90849280e-01,
         7.65092056e-01,  6.18852748e-01],
       [ 8.88693759e-02,  4.32843655e-01, -6.90849280e-01,
         7.65092056e-01,  6.18852748e-01],
       [ 3.07743736e+00,  1.48790007e+00, -6.90849280e-01,
         7.65092056e-01,  6.18852748e-01],
       [-1.39116246e+00, -6.22212755e-01, -6.90849280e-01,
         7.65092056e-01, -1.61589329e+00],
       [ 2.74754628e-02,  1.48790007e+00, -6.90849280e-01,
         7.65092056e-01,  6.18852748e-01],
       [-1.15326105e+00, -6.22212755e-01, -6.90849280e-01,
         7.65092056e-01,  6.18852748e-01],
       [-4.26890094e-02, -6.22212755e-01,  1.44749373e+00,
        -1.30703226e+00, -1.61589329e+00],
       [-7.71741728e-01, -6.22212755e-01,  1.44749373e+00,
         7.65092056e-01, -1.61589329e+00],
       [-4.70742889e-02,  1.48790007e+00, -6.90849280e-01,
         7.65092056e-01,  6.18852748e-01],
       [ 1.95919109e+00,  4.32843655e-01, -6.90849280e-01,
         7.65092056e-01,  6.18852748e-01],
       [ 7.00615868e-01,  4.32843655e-01, -6.90849280e-01,
        -1.30703226e+00,  6.18852748e-01],
       [ 8.88693759e-02, -6.22212755e-01, -6.90849280e-01,
        -1.30703226e+00,  6.18852748e-01],
       [ 4.76966613e-01,  1.48790007e+00, -6.90849280e-01,
         7.65092056e-01,  6.18852748e-01],
       [-4.25304647e-01, -6.22212755e-01,  1.44749373e+00,
        -1.30703226e+00,  6.18852748e-01],
       [-4.13245128e-01, -6.22212755e-01,  1.44749373e+00,
         7.65092056e-01, -1.61589329e+00],
       [-1.03376218e+00, -6.22212755e-01, -6.90849280e-01,
         7.65092056e-01,  6.18852748e-01],
       [ 4.11187420e-01, -6.22212755e-01, -6.90849280e-01,
         7.65092056e-01,  6.18852748e-01],
       [-3.51851215e-01, -6.22212755e-01,  1.44749373e+00,
         7.65092056e-01,  6.18852748e-01],
       [ 2.79629035e-01, -6.22212755e-01,  1.44749373e+00,
         7.65092056e-01,  6.18852748e-01],
       [ 2.18941826e+00,  1.48790007e+00, -6.90849280e-01,
        -1.30703226e+00,  6.18852748e-01],
       [-5.68922551e-01, -6.22212755e-01, -6.90849280e-01,
        -1.30703226e+00,  6.18852748e-01],
       [-2.36737628e-01, -6.22212755e-01, -6.90849280e-01,
         7.65092056e-01,  6.18852748e-01],
       [ 9.15494564e-01,  4.32843655e-01, -6.90849280e-01,
         7.65092056e-01,  6.18852748e-01],
       [ 1.60398345e+00,  1.48790007e+00,  1.44749373e+00,
         7.65092056e-01, -1.61589329e+00],
       [ 2.70858476e-01, -6.22212755e-01, -6.90849280e-01,
        -1.30703226e+00,  6.18852748e-01],
       [ 1.54587849e+00,  3.59801289e+00, -6.90849280e-01,
         7.65092056e-01, -1.61589329e+00],
       [ 2.10719427e+00,  1.48790007e+00, -6.90849280e-01,
         7.65092056e-01,  6.18852748e-01],
       [-8.00246045e-01, -6.22212755e-01,  1.44749373e+00,
        -1.30703226e+00,  6.18852748e-01],
       [ 7.51046582e-01,  3.59801289e+00,  1.44749373e+00,
         7.65092056e-01, -1.61589329e+00],
       [ 2.80725355e-01, -6.22212755e-01, -6.90849280e-01,
         7.65092056e-01, -1.61589329e+00],
       [-9.70175626e-01, -6.22212755e-01,  1.44749373e+00,
        -1.30703226e+00,  6.18852748e-01],
       [ 7.74170498e-03, -6.22212755e-01,  1.44749373e+00,
         7.65092056e-01, -1.61589329e+00],
       [-1.08090393e+00, -6.22212755e-01, -6.90849280e-01,
        -1.30703226e+00, -1.61589329e+00],
       [-2.60856665e-01, -6.22212755e-01, -6.90849280e-01,
         7.65092056e-01,  6.18852748e-01],
       [-1.25302615e+00, -6.22212755e-01, -6.90849280e-01,
         7.65092056e-01,  6.18852748e-01],
       [ 3.35642547e-03, -6.22212755e-01, -6.90849280e-01,
         7.65092056e-01,  6.18852748e-01],
       [-4.62579523e-01, -6.22212755e-01, -6.90849280e-01,
         7.65092056e-01, -1.61589329e+00],
       [-7.43237411e-01, -6.22212755e-01,  1.44749373e+00,
         7.65092056e-01, -1.61589329e+00],
       [-7.58585890e-01, -6.22212755e-01, -6.90849280e-01,
         7.65092056e-01,  6.18852748e-01],
       [ 2.23107842e+00, -6.22212755e-01, -6.90849280e-01,
        -1.30703226e+00,  6.18852748e-01],
       [ 2.03154820e+00,  1.48790007e+00, -6.90849280e-01,
        -1.30703226e+00,  6.18852748e-01],
       [-7.89282846e-01, -6.22212755e-01,  1.44749373e+00,
        -1.30703226e+00, -1.61589329e+00],
       [ 7.68098573e-02,  4.32843655e-01,  1.44749373e+00,
        -1.30703226e+00,  6.18852748e-01],
       [ 2.51124718e-01, -6.22212755e-01, -6.90849280e-01,
         7.65092056e-01,  6.18852748e-01],
       [-7.59682209e-01, -6.22212755e-01,  1.44749373e+00,
        -1.30703226e+00,  6.18852748e-01],
       [ 1.65112520e+00,  1.48790007e+00,  1.44749373e+00,
         7.65092056e-01,  6.18852748e-01],
       [ 4.25439578e-01,  1.48790007e+00,  1.44749373e+00,
         7.65092056e-01, -1.61589329e+00],
       [ 2.64219837e+00,  4.32843655e-01,  1.44749373e+00,
        -1.30703226e+00,  6.18852748e-01],
       [ 4.23246939e-01,  4.32843655e-01, -6.90849280e-01,
         7.65092056e-01,  6.18852748e-01],
       [ 6.80882110e-01, -6.22212755e-01,  1.44749373e+00,
         7.65092056e-01,  6.18852748e-01],
       [-1.04911066e+00, -6.22212755e-01,  1.44749373e+00,
        -1.30703226e+00,  6.18852748e-01],
       [-1.30883727e-02,  4.32843655e-01, -6.90849280e-01,
         7.65092056e-01,  6.18852748e-01],
       [-1.08090393e+00,  4.32843655e-01, -6.90849280e-01,
         7.65092056e-01,  6.18852748e-01],
       [-9.32900750e-01, -6.22212755e-01, -6.90849280e-01,
         7.65092056e-01, -1.61589329e+00],
       [-3.96800330e-01, -6.22212755e-01, -6.90849280e-01,
        -1.30703226e+00, -1.61589329e+00],
       [-6.86228778e-01, -6.22212755e-01, -6.90849280e-01,
         7.65092056e-01,  6.18852748e-01],
       [-5.30551355e-01, -6.22212755e-01, -6.90849280e-01,
        -1.30703226e+00,  6.18852748e-01],
       [-9.89909384e-01, -6.22212755e-01,  1.44749373e+00,
         7.65092056e-01, -1.61589329e+00],
       [-1.11050457e+00, -6.22212755e-01, -6.90849280e-01,
         7.65092056e-01,  6.18852748e-01],
       [-4.28593606e-01,  4.32843655e-01, -6.90849280e-01,
         7.65092056e-01,  6.18852748e-01],
       [-1.65476836e-01,  4.32843655e-01, -6.90849280e-01,
         7.65092056e-01,  6.18852748e-01],
       [-8.70410517e-01, -6.22212755e-01,  1.44749373e+00,
         7.65092056e-01, -1.61589329e+00],
       [-1.12475673e+00, -6.22212755e-01, -6.90849280e-01,
         7.65092056e-01,  6.18852748e-01],
       [-2.94842581e-01, -6.22212755e-01,  1.44749373e+00,
        -1.30703226e+00,  6.18852748e-01],
       [ 1.12489166e+00,  2.54295648e+00, -6.90849280e-01,
        -1.30703226e+00,  6.18852748e-01],
       [-9.66886666e-01, -6.22212755e-01,  1.44749373e+00,
         7.65092056e-01, -1.61589329e+00],
       [-2.65241945e-01, -6.22212755e-01, -6.90849280e-01,
         7.65092056e-01,  6.18852748e-01],
       [ 1.64515447e-01, -6.22212755e-01, -6.90849280e-01,
         7.65092056e-01,  6.18852748e-01],
       [ 3.25674470e-01,  1.48790007e+00, -6.90849280e-01,
        -1.30703226e+00,  6.18852748e-01],
       [ 6.04139718e-01,  4.32843655e-01,  1.44749373e+00,
         7.65092056e-01,  6.18852748e-01],
       [-7.00480936e-01, -6.22212755e-01, -6.90849280e-01,
         7.65092056e-01,  6.18852748e-01],
       [-7.75030688e-01, -6.22212755e-01, -6.90849280e-01,
         7.65092056e-01,  6.18852748e-01],
       [-2.02751712e-01,  1.48790007e+00, -6.90849280e-01,
         7.65092056e-01,  6.18852748e-01],
       [-1.63284196e-01,  4.32843655e-01, -6.90849280e-01,
        -1.30703226e+00, -1.61589329e+00],
       [-6.22642225e-01, -6.22212755e-01,  1.44749373e+00,
         7.65092056e-01, -1.61589329e+00],
       [ 5.37871398e-02,  2.54295648e+00, -6.90849280e-01,
         7.65092056e-01,  6.18852748e-01],
       [ 4.17765339e-01,  1.48790007e+00, -6.90849280e-01,
        -1.30703226e+00,  6.18852748e-01],
       [-1.10831193e+00, -6.22212755e-01,  1.44749373e+00,
        -1.30703226e+00, -1.61589329e+00],
       [-5.63440951e-01, -6.22212755e-01,  1.44749373e+00,
         7.65092056e-01,  6.18852748e-01],
       [ 1.26193165e+00,  1.48790007e+00, -6.90849280e-01,
         7.65092056e-01,  6.18852748e-01],
       [ 2.30124289e+00,  2.54295648e+00, -6.90849280e-01,
         7.65092056e-01, -1.61589329e+00],
       [ 3.62460218e-02,  1.48790007e+00, -6.90849280e-01,
        -1.30703226e+00, -1.61589329e+00],
       [-9.13166992e-01, -6.22212755e-01,  1.44749373e+00,
         7.65092056e-01, -1.61589329e+00],
       [-6.02301274e-02, -6.22212755e-01,  1.44749373e+00,
         7.65092056e-01,  6.18852748e-01],
       [-6.27027504e-01, -6.22212755e-01, -6.90849280e-01,
        -1.30703226e+00,  6.18852748e-01],
       [-8.48484120e-01, -6.22212755e-01, -6.90849280e-01,
         7.65092056e-01,  6.18852748e-01],
       [-1.11050457e+00, -1.67726916e+00,  1.44749373e+00,
         7.65092056e-01, -1.61589329e+00],
       [ 7.65298740e-01, -6.22212755e-01,  1.44749373e+00,
        -1.30703226e+00,  6.18852748e-01],
       [ 1.39239371e+00, -6.22212755e-01, -6.90849280e-01,
        -1.30703226e+00,  6.18852748e-01],
       [-3.18961619e-01, -6.22212755e-01, -6.90849280e-01,
         7.65092056e-01, -1.61589329e+00],
       [ 2.51173631e+00,  1.48790007e+00,  1.44749373e+00,
        -1.30703226e+00, -1.61589329e+00],
       [ 4.46269656e-01, -6.22212755e-01, -6.90849280e-01,
        -1.30703226e+00,  6.18852748e-01],
       [-3.16768979e-01, -6.22212755e-01,  1.44749373e+00,
         7.65092056e-01,  6.18852748e-01],
       [-1.14229785e+00, -6.22212755e-01, -6.90849280e-01,
         7.65092056e-01, -1.61589329e+00],
       [-8.33135641e-01, -6.22212755e-01, -6.90849280e-01,
        -1.30703226e+00,  6.18852748e-01],
       [ 7.30216504e-01, -6.22212755e-01,  1.44749373e+00,
        -1.30703226e+00,  6.18852748e-01],
       [ 7.67491380e-01,  1.48790007e+00, -6.90849280e-01,
         7.65092056e-01, -1.61589329e+00],
       [-2.61952985e-01,  1.48790007e+00, -6.90849280e-01,
         7.65092056e-01,  6.18852748e-01],
       [ 4.73677653e-01,  4.32843655e-01, -6.90849280e-01,
         7.65092056e-01,  6.18852748e-01],
       [-3.88029771e-01, -6.22212755e-01, -6.90849280e-01,
         7.65092056e-01, -1.61589329e+00],
       [ 2.10560882e-01, -6.22212755e-01,  1.44749373e+00,
        -1.30703226e+00,  6.18852748e-01],
       [-3.70488653e-01, -6.22212755e-01, -6.90849280e-01,
        -1.30703226e+00,  6.18852748e-01],
       [-9.41671309e-01, -6.22212755e-01, -6.90849280e-01,
         7.65092056e-01,  6.18852748e-01],
       [ 1.21369357e+00,  4.32843655e-01, -6.90849280e-01,
         7.65092056e-01,  6.18852748e-01],
       [-5.17395516e-01, -6.22212755e-01, -6.90849280e-01,
        -1.30703226e+00, -1.61589329e+00],
       [-9.82235145e-01, -6.22212755e-01, -6.90849280e-01,
        -1.30703226e+00,  6.18852748e-01],
       [-2.99227861e-01, -6.22212755e-01,  1.44749373e+00,
         7.65092056e-01, -1.61589329e+00],
       [ 4.94507731e-01, -6.22212755e-01, -6.90849280e-01,
         7.65092056e-01, -1.61589329e+00],
       [ 8.71641769e-01,  2.54295648e+00, -6.90849280e-01,
        -1.30703226e+00,  6.18852748e-01],
       [-8.96722194e-01, -6.22212755e-01, -6.90849280e-01,
         7.65092056e-01,  6.18852748e-01],
       [-2.10425951e-01, -6.22212755e-01, -6.90849280e-01,
         7.65092056e-01, -1.61589329e+00],
       [-4.26400967e-01,  4.32843655e-01, -6.90849280e-01,
         7.65092056e-01,  6.18852748e-01],
       [ 9.93434474e-03, -6.22212755e-01,  1.44749373e+00,
         7.65092056e-01,  6.18852748e-01],
       [ 6.23873476e-01,  1.48790007e+00, -6.90849280e-01,
        -1.30703226e+00,  6.18852748e-01],
       [-5.94137908e-01, -6.22212755e-01, -6.90849280e-01,
         7.65092056e-01,  6.18852748e-01],
       [ 2.43450479e-01, -6.22212755e-01,  1.44749373e+00,
        -1.30703226e+00,  6.18852748e-01],
       [-1.38568086e+00, -6.22212755e-01, -6.90849280e-01,
         7.65092056e-01, -1.61589329e+00],
       [-1.87792848e+00, -1.67726916e+00,  1.44749373e+00,
        -1.30703226e+00,  6.18852748e-01],
       [ 9.03435045e-01, -6.22212755e-01, -6.90849280e-01,
        -1.30703226e+00, -1.61589329e+00],
       [-1.04691802e+00, -6.22212755e-01,  1.44749373e+00,
         7.65092056e-01, -1.61589329e+00],
       [ 1.33757772e+00,  1.48790007e+00, -6.90849280e-01,
         7.65092056e-01,  6.18852748e-01],
       [-1.41966678e+00, -6.22212755e-01, -6.90849280e-01,
        -1.30703226e+00,  6.18852748e-01]])

In [165]:
sgd=SGDRegressor(max_iter=1000,learning_rate='constant',eta0=0.01)

In [166]:
sgd.fit(X_train,y_train)

SGDRegressor(learning_rate='constant')

In [167]:
y_pred=sgd.predict(X_test)

In [168]:
print(r2_score(y_test,y_pred))

0.5854128204835297