In [198]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import MinMaxScaler
from sklearn.pipeline import Pipeline,make_pipeline
from sklearn.feature_selection import SelectKBest,chi2
from sklearn.tree import DecisionTreeClassifier

In [199]:
df=pd.read_csv('train.csv')
df.head(2)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C

In [200]:
# name - drop
# sex , embarked- ohe
# cabin , ticket - remove alphabate 
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [201]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [202]:
X=df.drop(['Survived','Name','Ticket','Cabin'],axis=1)
y=df['Survived']

In [203]:
X.head()

   PassengerId  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0            1       3    male  22.0      1      0   7.2500        S
1            2       1  female  38.0      1      0  71.2833        C
2            3       3  female  26.0      0      0   7.9250        S
3            4       1  female  35.0      1      0  53.1000        S
4            5       3    male  35.0      0      0   8.0500        S

In [204]:
X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=0,test_size=0.2)

In [205]:
tr_si1=ColumnTransformer([
    ('imp_age',SimpleImputer(strategy='most_frequent'),[2]),
    ('imp_emb',SimpleImputer(strategy='most_frequent'),[7]),
],remainder='passthrough')

In [206]:
tr_ohe2=ColumnTransformer([
    ('ohe_',OneHotEncoder(handle_unknown='ignore'),[2,7])
],remainder='passthrough')

In [ ]:
tr_scal3=ColumnTransformer([
    ('scl_',MinMaxScaler(),slice(0,7)),
])

In [208]:
pipe=make_pipeline(tr_si1,tr_ohe2,tr_scal3)

In [209]:
X.sample()

     PassengerId  Pclass     Sex  Age  SibSp  Parch   Fare Embarked
109          110       3  female  NaN      1      0  24.15        Q

In [210]:
pipe.fit(X_train,y_train)

ValueError: For a sparse output, all columns should be a numeric or convertible to a numeric.